name = "mqwaba"
main = "src/index.ts"
compatibility_date = "2024-01-12"
account_id = "4f296275a5fa3d5c36343151790e96d3"
workers_dev = true

#[[queues.consumers]]
#queue = "mqwaba"
#max_batch_size = 10
#max_batch_timeout = 2
#retry_delay = 60

#[[queues.producers]]
#queue = "wchat"
#binding = "wchatmq"

[vars]
CELL_CASA = "160343020499275"
